### ISSUE TITLE
Empty lesson id causes upload failure to be reported

### ISSUE THREAD

**Issue by planetf1** [frankharkins/learning-content-tools#8]
For a course I am developing, I have one lesson which I want to publish to 'staging', but am not ready to publish to 'production'

I therefore have a lesson configured in iql.conf.yaml as follows:

```
  - path: lessons/Quiz
    idStaging: b49f924e-4173-ab7c-81c4-3f6eb0a8d3b0
    idProduction:
```

In this case, the upload tool will fail with:

❌ Push Quiz: Finding English translation...
Traceback (most recent call last):
File "/home/travis/virtualenv/python3.11.0/bin/sync-lessons", line 8, in
sys.exit(sync_lessons())
^^^^^^^^^^^^^^
File "/home/travis/virtualenv/python3.11.0/lib/python3.11/site-packages/iql_lesson_sync/init.py", line 55, in sync_lessons
api.push(lesson)
File "/home/travis/virtualenv/python3.11.0/lib/python3.11/site-packages/iql_lesson_sync/upload.py", line 93, in push
raise err
File "/home/travis/virtualenv/python3.11.0/lib/python3.11/site-packages/iql_lesson_sync/upload.py", line 82, in push
web_page = self._push(lesson, _log_fn)
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/travis/virtualenv/python3.11.0/lib/python3.11/site-packages/iql_lesson_sync/upload.py", line 123, in _push
response.raise_for_status()
File "/home/travis/virtualenv/python3.11.0/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://learning-api.quantum-computing.ibm.com/items/lessons/None?fields%5B%5D=translations.id,translations.languages_code

It would be useful to treat this as a warning (or successful) since it is performing as the user intends, and
the tool should run to completion.

originally in my case this lesson was mid way through my lesson list, so caused later lessons not to be published.  A little reordering means it's easy to workaround.

I can look at a PR once we're past our release...

**Comment by frankharkins** [comment]
@planetf1 thanks! Sorry I missed this.

Would #9 resolve this for you? You'd have to remove the `idProduction` line from your `iql.conf.yml`.

**Comment by planetf1** [comment]
@frankharkins yes that would be perfect - it's fine for us to remove that line.
Apologies - I didn't get around to the PR yet .. (back to some openssl/c coding work!)
